AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: create_order/
      Handler: main.go 
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-order
            Method: POST

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
        - SQSSendMessagePolicy:
            QueueName: 
              !GetAtt OrdersQueue.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - sqs:GetQueueUrl
              Resource: !GetAtt OrdersQueue.Arn
  
  ProcessPaymentFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: process_payment/
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - arm64

      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /process-payment
            Method: PUT

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentsTable
        - SQSSendMessagePolicy:
            QueueName: 
              !GetAtt PaymentsQueue.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - sqs:GetQueueUrl
              Resource: !GetAtt PaymentsQueue.Arn

  OrderCreatedFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: order_created/
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        OrderCreatedEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrdersQueue.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentsTable
        - SQSPollerPolicy:
            QueueName: !GetAtt OrdersQueue.QueueName

  PaymentProcessedFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: payment_processed/
      Handler: main.go
      Runtime: provided.al2
      Architectures:
        - arm64
      Events:
        PaymentProcessedEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt PaymentsQueue.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
        - SQSPollerPolicy:
            QueueName: !GetAtt PaymentsQueue.QueueName
            
  OrdersQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: orders-queue

  PaymentsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: payments-queue

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: orders
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
  PaymentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: payments
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
